apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feature-store-ingress
spec:
  rules:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feature-store
                port:
                  number: 8000
