apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-serving-ingress
spec:
  rules:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ml-serving
                port:
                  number: 8002
